// Flat UI-string dictionary for the app screens (dashboard, collection, chat,
// tests, templates, onboarding). Keyed by the original Russian string; each
// value is a 20-slot array matching LANGS order. translate() falls back to the
// Russian source if a language/string pair isn't found — never breaks the UI.

export const LANGS = [
  "ru", "uz", "kk", "uk", "az", "ky", "tg", "be", "hy", "ka",
  "tk", "en", "es", "pt", "ar", "tr", "hi", "ja", "ko", "de",
] as const;

export type Lang = (typeof LANGS)[number];

export const LANGUAGES: { code: Lang; native: string; rtl?: boolean }[] = [
  { code: "ru", native: "Русский" },
  { code: "uz", native: "O'zbekcha" },
  { code: "kk", native: "Қазақша" },
  { code: "uk", native: "Українська" },
  { code: "az", native: "Azərbaycanca" },
  { code: "ky", native: "Кыргызча" },
  { code: "tg", native: "Тоҷикӣ" },
  { code: "be", native: "Беларуская" },
  { code: "hy", native: "Հայերեն" },
  { code: "ka", native: "ქართული" },
  { code: "tk", native: "Türkmençe" },
  { code: "en", native: "English" },
  { code: "es", native: "Español" },
  { code: "pt", native: "Português" },
  { code: "ar", native: "العربية", rtl: true },
  { code: "tr", native: "Türkçe" },
  { code: "hi", native: "हिन्दी" },
  { code: "ja", native: "日本語" },
  { code: "ko", native: "한국어" },
  { code: "de", native: "Deutsch" },
];

const LANG_INDEX: Record<Lang, number> = Object.fromEntries(LANGS.map((l, i) => [l, i])) as Record<Lang, number>;

export function isRtl(lang: Lang): boolean {
  return lang === "ar";
}

// English names, in LANGS order — used server-side to tell the AI which
// language to write generated content in (test questions, grading feedback),
// since asking it to answer "in the language of the text" ignores the UI
// language the user actually picked.
const LANGUAGE_NAMES_LIST = [
  "Russian", "Uzbek", "Kazakh", "Ukrainian", "Azerbaijani", "Kyrgyz", "Tajik", "Belarusian",
  "Armenian", "Georgian", "Turkmen", "English", "Spanish", "Portuguese", "Arabic", "Turkish",
  "Hindi", "Japanese", "Korean", "German",
];

export function languageName(lang: Lang): string {
  return pick(lang, LANGUAGE_NAMES_LIST);
}

// order: ru, uz, kk, uk, az, ky, tg, be, hy, ka, tk, en, es, pt, ar, tr, hi, ja, ko, de
const UI_DICT: Record<string, string[]> = {
  "Загрузка...": ["Загрузка...", "Yuklanmoqda...", "Жүктелуде...", "Завантаження...", "Yüklənir...", "Жүктөлүүдө...", "Боргузӣ шуда истодааст...", "Загрузка...", "Բեռնում...", "იტვირთება...", "Ýüklenýär...", "Loading...", "Cargando...", "Carregando...", "جارٍ التحميل...", "Yükleniyor...", "लोड हो रहा है...", "読み込み中...", "로딩 중...", "Wird geladen..."],
  "Отмена": ["Отмена", "Bekor qilish", "Бас тарту", "Скасувати", "Ləğv et", "Жокко чыгаруу", "Бекор кардан", "Скасаваць", "Չեղարկել", "გაუქმება", "Ýatyr", "Cancel", "Cancelar", "Cancelar", "إلغاء", "İptal", "रद्द करें", "キャンセル", "취소", "Abbrechen"],
  "Удалить": ["Удалить", "O'chirish", "Жою", "Видалити", "Sil", "Өчүрүү", "Нест кардан", "Выдаліць", "Ջնջել", "წაშლა", "Poz", "Delete", "Eliminar", "Excluir", "حذف", "Sil", "हटाएं", "削除", "삭제", "Löschen"],
  "Готово": ["Готово", "Tayyor", "Дайын", "Готово", "Hazır", "Даяр", "Тайёр", "Гатова", "Պատրաստ է", "მზადაა", "Taýýar", "Ready", "Listo", "Pronto", "جاهز", "Hazır", "तैयार", "完了", "완료", "Fertig"],
  "Ошибка": ["Ошибка", "Xato", "Қате", "Помилка", "Xəta", "Ката", "Хато", "Памылка", "Սխալ", "შეცდომა", "Ýalňyşlyk", "Error", "Error", "Erro", "خطأ", "Hata", "त्रुटि", "エラー", "오류", "Fehler"],
  "Обрабатывается...": ["Обрабатывается...", "Ishlov berilmoqda...", "Өңделуде...", "Обробляється...", "İşlənir...", "Иштелип жатат...", "Дар ҳоли коркард...", "Апрацоўваецца...", "Մշակվում է...", "მუშავდება...", "Işlenýär...", "Processing...", "Procesando...", "Processando...", "قيد المعالجة...", "İşleniyor...", "प्रोसेस हो रहा है...", "処理中...", "처리 중...", "Wird verarbeitet..."],
  "Раздел": ["Раздел", "Bo'lim", "Бөлім", "Розділ", "Bölmə", "Бөлүм", "Бахш", "Раздзел", "Բաժին", "განყოფილება", "Bölüm", "Section", "Sección", "Seção", "قسم", "Bölüm", "अनुभाग", "セクション", "섹션", "Bereich"],
  "Тест": ["Тест", "Test", "Тест", "Тест", "Test", "Тест", "Тест", "Тэст", "Թեստ", "ტესტი", "Test", "Test", "Test", "Teste", "اختبار", "Test", "टेस्ट", "テスト", "테스트", "Test"],
  "Шаблоны": ["Шаблоны", "Shablonlar", "Үлгілер", "Шаблони", "Şablonlar", "Шаблондор", "Андозаҳо", "Шаблоны", "Ձևանմուշներ", "შაბლონები", "Şablonlar", "Templates", "Plantillas", "Modelos", "القوالب", "Şablonlar", "टेम्पलेट्स", "テンプレート", "템플릿", "Vorlagen"],
  "Подписка": ["Подписка", "Obuna", "Жазылым", "Підписка", "Abunə", "Жазылуу", "Обуна", "Падпіска", "Բաժանորդագրություն", "გამოწერა", "Abuna", "Subscription", "Suscripción", "Assinatura", "الاشتراك", "Abonelik", "सदस्यता", "サブスクリプション", "구독", "Abonnement"],
  "Premium подписка активна": ["Premium подписка активна", "Premium obuna faol", "Premium жазылым белсенді", "Premium підписка активна", "Premium abunə aktivdir", "Premium жазылуу активдүү", "Обунаи Premium фаъол аст", "Premium падпіска актыўная", "Premium բաժանորդագրությունն ակտիվ է", "Premium გამოწერა აქტიურია", "Premium abuna işjeň", "Premium subscription active", "Suscripción Premium activa", "Assinatura Premium ativa", "اشتراك Premium نشط", "Premium abonelik aktif", "Premium सदस्यता सक्रिय है", "プレミアムサブスクリプション有効", "프리미엄 구독 활성화됨", "Premium-Abonnement aktiv"],
  "Активна до": ["Активна до", "Amal qiladi", "Дейін белсенді", "Активна до", "Aktivdir", "Чейин активдүү", "То фаъол аст", "Актыўная да", "Ակտիվ է մինչև", "აქტიურია მდე", "Çenli işjeň", "Active until", "Activa hasta", "Ativa até", "نشط حتى", "Şu tarihe kadar aktif", "तक सक्रिय", "有効期限", "활성 기한", "Aktiv bis"],
  "мес": ["мес", "oy", "ай", "міс", "ay", "ай", "моҳ", "мес", "ամիս", "თვე", "aý", "mo", "mes", "mês", "شهر", "ay", "माह", "月", "월", "Monat"],
  "Без ограничений на разделы, книги и вопросы": ["Без ограничений на разделы, книги и вопросы", "Bo'limlar, kitoblar va savollarga cheklov yo'q", "Бөлімдер, кітаптар және сұрақтарға шектеу жоқ", "Без обмежень на розділи, книги та запитання", "Bölmə, kitab və suallara məhdudiyyət yoxdur", "Бөлүмдөргө, китептерге жана суроолорго чектөө жок", "Бе маҳдудият дар бахшҳо, китобҳо ва саволҳо", "Без абмежаванняў на раздзелы, кнігі і пытанні", "Առանց սահմանափակման բաժինների, գրքերի և հարցերի համար", "შეზღუდვების გარეშე განყოფილებებზე, წიგნებზე და კითხვებზე", "Bölümlere, kitaplara we soraglara çäklendirme ýok", "No limits on sections, books, or questions", "Sin límites en secciones, libros o preguntas", "Sem limites em seções, livros ou perguntas", "بدون حدود على الأقسام أو الكتب أو الأسئلة", "Bölümler, kitaplar ve sorular için sınır yok", "अनुभाग, किताबें और सवालों की कोई सीमा नहीं", "セクション、書籍、質問に制限なし", "섹션, 책, 질문에 제한 없음", "Keine Limits bei Bereichen, Büchern oder Fragen"],
  "Оплатить": ["Оплатить", "To'lash", "Төлеу", "Оплатити", "Ödə", "Төлөө", "Пардохт кардан", "Заплаціць", "Վճարել", "გადახდა", "Töle", "Pay", "Pagar", "Pagar", "الدفع", "Öde", "भुगतान करें", "支払う", "결제하기", "Bezahlen"],
  "Забыли пароль?": ["Забыли пароль?", "Parolni unutdingizmi?", "Құпия сөзді ұмыттыңыз ба?", "Забули пароль?", "Şifrəni unutmusunuz?", "Сырсөздү унуттуңузбу?", "Рамзро фаромӯш кардед?", "Забылі пароль?", "Մոռացե՞լ եք գաղտնաբառը", "დაგავიწყდათ პაროლი?", "Parolyňyzy unutdyňyzmy?", "Forgot password?", "¿Olvidaste tu contraseña?", "Esqueceu a senha?", "هل نسيت كلمة المرور؟", "Şifrenizi mi unuttunuz?", "पासवर्ड भूल गए?", "パスワードをお忘れですか？", "비밀번호를 잊으셨나요?", "Passwort vergessen?"],
  "Введите email, на который зарегистрирован аккаунт": ["Введите email, на который зарегистрирован аккаунт", "Ro'yxatdan o'tgan email manzilingizni kiriting", "Тіркелген email мекенжайыңызды енгізіңіз", "Введіть email, на який зареєстровано акаунт", "Hesabın qeydiyyatdan keçdiyi email-i daxil edin", "Каттоодон өткөн email дарегиңизди киргизиңиз", "Почтаи электронии сабтшударо ворид кунед", "Увядзіце email, на які зарэгістраваны акаунт", "Մուտքագրեք հաշվի գրանցման էլ. հասցեն", "შეიყვანეთ ანგარიშის რეგისტრაციის ელფოსტა", "Hasaba alnan email salgyňyzy giriziň", "Enter the email your account is registered with", "Introduce el email con el que te registraste", "Digite o email com o qual a conta foi registrada", "أدخل البريد الإلكتروني المسجل به الحساب", "Hesabın kayıtlı olduğu e-postayı girin", "जिस ईमेल से खाता पंजीकृत है वह दर्ज करें", "アカウント登録に使用したメールアドレスを入力してください", "계정이 등록된 이메일을 입력하세요", "Geben Sie die E-Mail-Adresse Ihres Kontos ein"],
  "Письмо со ссылкой для сброса пароля отправлено на почту": ["Письмо со ссылкой для сброса пароля отправлено на почту", "Parolni tiklash havolasi emailga yuborildi", "Құпия сөзді қалпына келтіру сілтемесі поштаға жіберілді", "Лист із посиланням для скидання пароля надіслано на пошту", "Şifrə sıfırlama linki emailə göndərildi", "Сырсөздү калыбына келтирүү шилтемеси почтага жөнөтүлдү", "Пайванди барқарорсозии рамз ба почта фиристода шуд", "Ліст са спасылкай для скіду пароля адпраўлены на пошту", "Գաղտնաբառի վերականգնման հղումն ուղարկվել է էլ. փոստին", "პაროლის აღდგენის ბმული გამოგზავნილია ელფოსტაზე", "Paroly dikeltmek üçin salgy e-poçta iberildi", "A password reset link has been sent to your email", "Se envió un enlace para restablecer la contraseña a tu email", "Um link para redefinir a senha foi enviado ao seu email", "تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني", "Şifre sıfırlama bağlantısı e-postanıza gönderildi", "पासवर्ड रीसेट लिंक आपके ईमेल पर भेज दिया गया है", "パスワードリセットのリンクをメールで送信しました", "비밀번호 재설정 링크가 이메일로 전송되었습니다", "Ein Link zum Zurücksetzen des Passworts wurde an Ihre E-Mail gesendet"],
  "Конфиденциальность": ["Конфиденциальность", "Maxfiylik", "Құпиялылық", "Конфіденційність", "Məxfilik", "Купуялуулук", "Махфият", "Канфідэнцыйнасць", "Գաղտնիություն", "კონფიდენციალურობა", "Gizlinlik", "Privacy", "Privacidad", "Privacidade", "الخصوصية", "Gizlilik", "गोपनीयता", "プライバシー", "개인정보 처리방침", "Datenschutz"],
  "Оплатить через Google Play": ["Оплатить через Google Play", "Google Play orqali to'lash", "Google Play арқылы төлеу", "Оплатити через Google Play", "Google Play ilə ödə", "Google Play аркылуу төлөө", "Тавассути Google Play пардохт кардан", "Заплаціць праз Google Play", "Վճարել Google Play-ով", "გადახდა Google Play-ით", "Google Play arkaly töle", "Pay via Google Play", "Pagar con Google Play", "Pagar com Google Play", "الدفع عبر Google Play", "Google Play ile öde", "Google Play से भुगतान करें", "Google Playで支払う", "Google Play로 결제하기", "Über Google Play bezahlen"],
  "Пробный период закончился": ["Пробный период закончился", "Sinov muddati tugadi", "Сынақ мерзімі аяқталды", "Пробний період закінчився", "Sınaq müddəti bitdi", "Сыноо мөөнөтү аяктады", "Давраи озмоишӣ ба итмом расид", "Пробны перыяд скончыўся", "Փորձնական շրջանն ավարտվել է", "საცდელი პერიოდი დასრულდა", "Synag möhleti gutardy", "Trial period has ended", "El período de prueba ha terminado", "O período de teste terminou", "انتهت الفترة التجريبية", "Deneme süresi doldu", "ट्रायल अवधि समाप्त हो गई", "トライアル期間が終了しました", "체험 기간이 종료되었습니다", "Die Testphase ist beendet"],
  "Чтобы продолжить пользоваться KnowledgeAI, оформите подписку — $5/мес.": ["Чтобы продолжить пользоваться KnowledgeAI, оформите подписку — $5/мес.", "KnowledgeAI'dan foydalanishni davom ettirish uchun obuna bo'ling — oyiga $5.", "KnowledgeAI-ды пайдалануды жалғастыру үшін жазылым рәсімдеңіз — айына $5.", "Щоб продовжити користуватися KnowledgeAI, оформіть підписку — $5/міс.", "KnowledgeAI-dan istifadəni davam etdirmək üçün abunə olun — ayda $5.", "KnowledgeAI колдонууну улантуу үчүн жазылууну тариздеңиз — айына $5.", "Барои идома додани истифодаи KnowledgeAI обуна шавед — 5 доллар дар моҳ.", "Каб працягнуць карыстацца KnowledgeAI, аформіце падпіску — $5/мес.", "KnowledgeAI-ից շարունակելու համար բաժանորդագրվեք՝ $5/ամսական։", "KnowledgeAI-ის გამოყენების გასაგრძელებლად გააფორმეთ გამოწერა — $5/თვე.", "KnowledgeAI-dan peýdalanmagy dowam etdirmek üçin abuna boluň — aýda $5.", "To keep using KnowledgeAI, subscribe — $5/mo.", "Para seguir usando KnowledgeAI, suscríbete — $5/mes.", "Para continuar usando o KnowledgeAI, assine — $5/mês.", "لمتابعة استخدام KnowledgeAI، اشترك — 5 دولارات شهرياً.", "KnowledgeAI'ı kullanmaya devam etmek için abone olun — ayda $5.", "KnowledgeAI का उपयोग जारी रखने के लिए सदस्यता लें — $5/माह।", "KnowledgeAIを引き続き利用するには登録してください — 月$5。", "KnowledgeAI를 계속 사용하려면 구독하세요 — 월 $5.", "Um KnowledgeAI weiter zu nutzen, abonnieren Sie — $5/Monat."],
  "Оформить подписку": ["Оформить подписку", "Obunani rasmiylashtirish", "Жазылымды рәсімдеу", "Оформити підписку", "Abunə ol", "Жазылууну тариздөө", "Обунаро расмӣ кардан", "Аформіць падпіску", "Ձևակերպել բաժանորդագրություն", "გამოწერის გაფორმება", "Abuna bolmak", "Upgrade", "Suscribirse", "Assinar", "الاشتراك الآن", "Abone ol", "सदस्यता लें", "サブスクリプションに登録", "구독하기", "Abonnieren"],
  "На бесплатном тарифе доступно не более 2 разделов. Оформите подписку, чтобы снять ограничение.": ["На бесплатном тарифе доступно не более 2 разделов. Оформите подписку, чтобы снять ограничение.", "Bepul tarifda 2 tadan ortiq bo'lim yaratib bo'lmaydi. Cheklovni olib tashlash uchun obuna bo'ling.", "Тегін тарифте 2-ден артық бөлім жасауға болмайды. Шектеуді алып тастау үшін жазылым рәсімдеңіз.", "На безкоштовному тарифі доступно не більше 2 розділів. Оформіть підписку, щоб зняти обмеження.", "Pulsuz tarifdə 2-dən çox bölmə yaratmaq olmaz. Məhdudiyyəti aradan qaldırmaq üçün abunə olun.", "Акысыз тарифте 2ден ашык бөлүм түзүүгө болбойт. Чектөөнү алып салуу үчүн жазылууну тариздеңиз.", "Дар нархномаи ройгон на бештар аз 2 бахш сохтан мумкин аст. Барои бартараф кардани маҳдудият обуна шавед.", "На бясплатным тарыфе даступна не больш за 2 раздзелы. Аформіце падпіску, каб зняць абмежаванне.", "Անվճար պլանում հասանելի է առավելագույնը 2 բաժին։ Բաժանորդագրվեք՝ սահմանափակումը հանելու համար։", "უფასო ტარიფზე ხელმისაწვდომია არაუმეტეს 2 განყოფილება. მოხსენით შეზღუდვა გამოწერით.", "Mugt tarifde 2-den köp bölüm döredip bolmaýar. Çäklendirmäni aýyrmak üçin abuna boluň.", "The free plan allows up to 2 sections. Subscribe to remove the limit.", "El plan gratuito permite hasta 2 secciones. Suscríbete para eliminar el límite.", "O plano gratuito permite até 2 seções. Assine para remover o limite.", "الخطة المجانية تسمح بحد أقصى قسمين. اشترك لإزالة الحد.", "Ücretsiz planda en fazla 2 bölüm oluşturabilirsiniz. Sınırı kaldırmak için abone olun.", "मुफ़्त प्लान में अधिकतम 2 अनुभाग की अनुमति है। सीमा हटाने के लिए सदस्यता लें।", "無料プランでは最大2セクションまでです。制限を解除するには登録してください。", "무료 플랜은 최대 2개 섹션까지 가능합니다. 제한을 해제하려면 구독하세요.", "Der kostenlose Plan erlaubt bis zu 2 Bereiche. Abonnieren Sie, um das Limit aufzuheben."],
  "На бесплатном тарифе доступно не более 5 книг. Оформите подписку, чтобы снять ограничение.": ["На бесплатном тарифе доступно не более 5 книг. Оформите подписку, чтобы снять ограничение.", "Bepul tarifda 5 tadan ortiq kitob yuklab bo'lmaydi. Cheklovni olib tashlash uchun obuna bo'ling.", "Тегін тарифте 5-тен артық кітап жүктеуге болмайды. Шектеуді алып тастау үшін жазылым рәсімдеңіз.", "На безкоштовному тарифі доступно не більше 5 книг. Оформіть підписку, щоб зняти обмеження.", "Pulsuz tarifdə 5-dən çox kitab yükləmək olmaz. Məhdudiyyəti aradan qaldırmaq üçün abunə olun.", "Акысыз тарифте 5тен ашык китеп жүктөөгө болбойт. Чектөөнү алып салуу үчүн жазылууну тариздеңиз.", "Дар нархномаи ройгон на бештар аз 5 китоб бор кардан мумкин аст. Барои бартараф кардани маҳдудият обуна шавед.", "На бясплатным тарыфе даступна не больш за 5 кніг. Аформіце падпіску, каб зняць абмежаванне.", "Անվճար պլանում հասանելի է առավելագույնը 5 գիրք։ Բաժանորդագրվեք՝ սահմանափակումը հանելու համար։", "უფასო ტარიფზე ხელმისაწვდომია არაუმეტეს 5 წიგნი. მოხსენით შეზღუდვა გამოწერით.", "Mugt tarifde 5-den köp kitap ýüklap bolmaýar. Çäklendirmäni aýyrmak üçin abuna boluň.", "The free plan allows up to 5 books. Subscribe to remove the limit.", "El plan gratuito permite hasta 5 libros. Suscríbete para eliminar el límite.", "O plano gratuito permite até 5 livros. Assine para remover o limite.", "الخطة المجانية تسمح بحد أقصى 5 كتب. اشترك لإزالة الحد.", "Ücretsiz planda en fazla 5 kitap yükleyebilirsiniz. Sınırı kaldırmak için abone olun.", "मुफ़्त प्लान में अधिकतम 5 किताबों की अनुमति है। सीमा हटाने के लिए सदस्यता लें।", "無料プランでは最大5冊までです。制限を解除するには登録してください。", "무료 플랜은 최대 5권까지 가능합니다. 제한을 해제하려면 구독하세요.", "Der kostenlose Plan erlaubt bis zu 5 Bücher. Abonnieren Sie, um das Limit aufzuheben."],
  "Обрабатываем оплату...": ["Обрабатываем оплату...", "To'lov qayta ishlanmoqda...", "Төлем өңделуде...", "Обробляємо оплату...", "Ödəniş işlənir...", "Төлөм иштелип жатат...", "Пардохт коркард шуда истодааст...", "Апрацоўваем аплату...", "Վճարումը մշակվում է...", "გადახდის დამუშავება...", "Töleg işlenýär...", "Processing payment...", "Procesando el pago...", "Processando o pagamento...", "جارٍ معالجة الدفع...", "Ödeme işleniyor...", "भुगतान संसाधित हो रहा है...", "支払いを処理中...", "결제 처리 중...", "Zahlung wird verarbeitet..."],
  "Файл пустой или текст не найден": ["Файл пустой или текст не найден", "Fayl bo'sh yoki matn topilmadi", "Файл бос немесе мәтін табылмады", "Файл порожній або текст не знайдено", "Fayl boşdur və ya mətn tapılmadı", "Файл бош же текст табылган жок", "Файл холӣ ё матн ёфт нашуд", "Файл пусты альбо тэкст не знойдзены", "Ֆայլը դատարկ է կամ տեքստ չի գտնվել", "ფაილი ცარიელია ან ტექსტი ვერ მოიძებნა", "Faýl boş ýa-da tekst tapylmady", "File is empty or no text was found", "El archivo está vacío o no se encontró texto", "O arquivo está vazio ou o texto não foi encontrado", "الملف فارغ أو لم يتم العثور على نص", "Dosya boş veya metin bulunamadı", "फ़ाइल खाली है या टेक्स्ट नहीं मिला", "ファイルが空か、テキストが見つかりません", "파일이 비어 있거나 텍스트를 찾을 수 없습니다", "Datei ist leer oder es wurde kein Text gefunden"],
  "Ошибка при чтении файла": ["Ошибка при чтении файла", "Faylni o'qishda xato", "Файлды оқу қатесі", "Помилка при читанні файлу", "Faylı oxuyarkən xəta", "Файлды окууда ката", "Хатогӣ ҳангоми хондани файл", "Памылка пры чытанні файла", "Ֆայլը կարդալու սխալ", "ფაილის წაკითხვის შეცდომა", "Faýly okamakda ýalňyşlyk", "Error reading the file", "Error al leer el archivo", "Erro ao ler o arquivo", "خطأ في قراءة الملف", "Dosya okunurken hata", "फ़ाइल पढ़ने में त्रुटि", "ファイルの読み込みエラー", "파일 읽기 오류", "Fehler beim Lesen der Datei"],
  "Ошибка при загрузке ссылки": ["Ошибка при загрузке ссылки", "Havolani yuklashda xato", "Сілтемені жүктеу қатесі", "Помилка при завантаженні посилання", "Linki yükləyərkən xəta", "Шилтемени жүктөөдө ката", "Хатогӣ ҳангоми боргирии истинод", "Памылка пры загрузцы спасылкі", "Հղումը բեռնելու սխալ", "ბმულის ჩატვირთვის შეცდომა", "Salgyny ýüklemekde ýalňyşlyk", "Error loading the link", "Error al cargar el enlace", "Erro ao carregar o link", "خطأ في تحميل الرابط", "Bağlantı yüklenirken hata", "लिंक लोड करने में त्रुटि", "リンクの読み込みエラー", "링크 로드 오류", "Fehler beim Laden des Links"],
  "Извлекаем текст...": ["Извлекаем текст...", "Matn ajratilmoqda...", "Мәтін алынуда...", "Витягуємо текст...", "Mətn çıxarılır...", "Текст алынууда...", "Матн истихроҷ шуда истодааст...", "Здабываем тэкст...", "Տեքստը հանվում է...", "ტექსტის ამოღება...", "Tekst alynýar...", "Extracting text...", "Extrayendo texto...", "Extraindo texto...", "جارٍ استخراج النص...", "Metin çıkarılıyor...", "टेक्स्ट निकाला जा रहा है...", "テキストを抽出中...", "텍스트 추출 중...", "Text wird extrahiert..."],
  "Подождите немного": ["Подождите немного", "Biroz kuting", "Сәл күте тұрыңыз", "Зачекайте трохи", "Bir az gözləyin", "Бир аз күтө туруңуз", "Каме сабр кунед", "Крыху пачакайце", "Մի փոքր սպասեք", "დაელოდეთ ცოტა ხანს", "Azajyk garaşyň", "Please wait a moment", "Espere un momento", "Aguarde um momento", "الرجاء الانتظار قليلاً", "Biraz bekleyin", "थोड़ा इंतज़ार करें", "少々お待ちください", "잠시만 기다려주세요", "Bitte warten Sie kurz"],
  "Загружаем страницу...": ["Загружаем страницу...", "Sahifa yuklanmoqda...", "Бет жүктелуде...", "Завантажуємо сторінку...", "Səhifə yüklənir...", "Барак жүктөлүүдө...", "Саҳифа боргузӣ шуда истодааст...", "Загружаем старонку...", "Էջը բեռնվում է...", "გვერდის ჩატვირთვა...", "Sahypa ýüklenýär...", "Loading the page...", "Cargando la página...", "Carregando a página...", "جارٍ تحميل الصفحة...", "Sayfa yükleniyor...", "पेज लोड हो रहा है...", "ページを読み込み中...", "페이지 로딩 중...", "Seite wird geladen..."],
  "Создать тест": ["Создать тест", "Test yaratish", "Тест құру", "Створити тест", "Test yarat", "Тест түзүү", "Тест сохтан", "Стварыць тэст", "Ստեղծել թեստ", "ტესტის შექმნა", "Test döret", "Create a test", "Crear un test", "Criar um teste", "إنشاء اختبار", "Test oluştur", "टेस्ट बनाएं", "テストを作成", "테스트 만들기", "Test erstellen"],
  "Готовим вопросы...": ["Готовим вопросы...", "Savollar tayyorlanmoqda...", "Сұрақтар дайындалуда...", "Готуємо запитання...", "Suallar hazırlanır...", "Суроолор даярдалууда...", "Саволҳо омода шуда истодаанд...", "Рыхтуем пытанні...", "Հարցեր են պատրաստվում...", "კითხვების მომზადება...", "Soraglar taýýarlanýar...", "Preparing questions...", "Preparando preguntas...", "Preparando perguntas...", "جارٍ إعداد الأسئلة...", "Sorular hazırlanıyor...", "प्रश्न तैयार किए जा रहे हैं...", "問題を準備中...", "질문 준비 중...", "Fragen werden vorbereitet..."],
  "Формат": ["Формат", "Format", "Формат", "Формат", "Format", "Формат", "Формат", "Фармат", "Ձևաչափ", "ფორმატი", "Format", "Format", "Formato", "Formato", "التنسيق", "Format", "फ़ॉर्मेट", "形式", "형식", "Format"],
  "С вариантами": ["С вариантами", "Variantlar bilan", "Нұсқалармен", "З варіантами", "Variantlarla", "Варианттар менен", "Бо вариантҳо", "З варыянтамі", "Տարբերակներով", "ვარიანტებით", "Wariantlar bilen", "Multiple choice", "Con opciones", "Com opções", "مع خيارات", "Seçenekli", "विकल्पों के साथ", "選択肢あり", "객관식", "Mit Auswahlmöglichkeiten"],
  "Открытые вопросы": ["Открытые вопросы", "Ochiq savollar", "Ашық сұрақтар", "Відкриті запитання", "Açıq suallar", "Ачык суроолор", "Саволҳои кушод", "Адкрытыя пытанні", "Բաց հարցեր", "ღია კითხვები", "Açyk soraglar", "Open-ended questions", "Preguntas abiertas", "Perguntas abertas", "أسئلة مفتوحة", "Açık uçlu sorular", "खुले प्रश्न", "記述式", "주관식", "Offene Fragen"],
  "Количество вопросов": ["Количество вопросов", "Savollar soni", "Сұрақтар саны", "Кількість запитань", "Sualların sayı", "Суроолордун саны", "Шумораи саволҳо", "Колькасць пытанняў", "Հարցերի քանակը", "კითხვების რაოდენობა", "Soraglaryň sany", "Number of questions", "Cantidad de preguntas", "Número de perguntas", "عدد الأسئلة", "Soru sayısı", "प्रश्नों की संख्या", "問題数", "질문 수", "Anzahl der Fragen"],
  "Сгенерировать": ["Сгенерировать", "Yaratish", "Жасау", "Згенерувати", "Yarat", "Түзүү", "Тавлид кардан", "Згенераваць", "Ստեղծել", "გენერაცია", "Döretmek", "Generate", "Generar", "Gerar", "إنشاء", "Oluştur", "जनरेट करें", "生成", "생성", "Generieren"],
  "Ошибка при создании теста": ["Ошибка при создании теста", "Testni yaratishda xato", "Тест құру қатесі", "Помилка при створенні тесту", "Test yaradarkən xəta", "Тест түзүүдө ката", "Хатогӣ ҳангоми сохтани тест", "Памылка пры стварэнні тэста", "Թեստ ստեղծելու սխալ", "ტესტის შექმნის შეცდომა", "Test döretmekde ýalňyşlyk", "Error creating the test", "Error al crear el test", "Erro ao criar o teste", "خطأ في إنشاء الاختبار", "Test oluşturulurken hata", "टेस्ट बनाने में त्रुटि", "テスト作成エラー", "테스트 생성 오류", "Fehler beim Erstellen des Tests"],
  "Вопросы не найдены": ["Вопросы не найдены", "Savollar topilmadi", "Сұрақтар табылмады", "Запитання не знайдено", "Suallar tapılmadı", "Суроолор табылган жок", "Саволҳо ёфт нашуданд", "Пытанні не знойдзены", "Հարցեր չեն գտնվել", "კითხვები ვერ მოიძებნა", "Soraglar tapylmady", "No questions found", "No se encontraron preguntas", "Nenhuma pergunta encontrada", "لم يتم العثور على أسئلة", "Soru bulunamadı", "कोई प्रश्न नहीं मिला", "問題が見つかりません", "질문을 찾을 수 없습니다", "Keine Fragen gefunden"],
  "Результат": ["Результат", "Natija", "Нәтиже", "Результат", "Nəticə", "Натыйжа", "Натиҷа", "Вынік", "Արդյունք", "შედეგი", "Netije", "Result", "Resultado", "Resultado", "النتيجة", "Sonuç", "परिणाम", "結果", "결과", "Ergebnis"],
  "Ваш ответ": ["Ваш ответ", "Javobingiz", "Сіздің жауабыңыз", "Ваша відповідь", "Cavabınız", "Сиздин жообуңуз", "Ҷавоби шумо", "Ваш адказ", "Ձեր պատասխանը", "თქვენი პასუხი", "Siziň jogabyňyz", "Your answer", "Su respuesta", "Sua resposta", "إجابتك", "Cevabınız", "आपका उत्तर", "あなたの回答", "회원님의 답변", "Ihre Antwort"],
  "Правильный ответ": ["Правильный ответ", "To'g'ri javob", "Дұрыс жауап", "Правильна відповідь", "Düzgün cavab", "Туура жооп", "Ҷавоби дуруст", "Правільны адказ", "Ճիշտ պատասխանը", "სწორი პასუხი", "Dogry jogap", "Correct answer", "Respuesta correcta", "Resposta correta", "الإجابة الصحيحة", "Doğru cevap", "सही उत्तर", "正解", "정답", "Richtige Antwort"],
  "Вернуться к разделу": ["Вернуться к разделу", "Bo'limga qaytish", "Бөлімге оралу", "Повернутися до розділу", "Bölməyə qayıt", "Бөлүмгө кайтуу", "Бозгашт ба бахш", "Вярнуцца да раздзела", "Վերադառնալ բաժին", "განყოფილებაში დაბრუნება", "Bölüme dolan", "Back to section", "Volver a la sección", "Voltar à seção", "العودة إلى القسم", "Bölüme dön", "अनुभाग पर वापस जाएं", "セクションに戻る", "섹션으로 돌아가기", "Zurück zum Bereich"],
  "Напишите ваш ответ...": ["Напишите ваш ответ...", "Javobingizni yozing...", "Жауабыңызды жазыңыз...", "Напишіть вашу відповідь...", "Cavabınızı yazın...", "Жообуңузду жазыңыз...", "Ҷавоби худро нависед...", "Напішыце свой адказ...", "Գրեք ձեր պատասխանը...", "დაწერეთ თქვენი პასუხი...", "Jogabyňyzy ýazyň...", "Write your answer...", "Escriba su respuesta...", "Escreva sua resposta...", "اكتب إجابتك...", "Cevabınızı yazın...", "अपना उत्तर लिखें...", "回答を入力してください...", "답변을 작성하세요...", "Schreiben Sie Ihre Antwort..."],
  "Проверяем...": ["Проверяем...", "Tekshirilmoqda...", "Тексерілуде...", "Перевіряємо...", "Yoxlanılır...", "Текшерилүүдө...", "Санҷида шуда истодааст...", "Правяраем...", "Ստուգվում է...", "მოწმდება...", "Barlanýar...", "Checking...", "Comprobando...", "Verificando...", "جارٍ التحقق...", "Kontrol ediliyor...", "जांच हो रही है...", "確認中...", "확인 중...", "Wird überprüft..."],
  "Завершить тест": ["Завершить тест", "Yakunlash", "Тестті аяқтау", "Завершити тест", "Testi bitir", "Тестти аяктоо", "Ба итмом расондани тест", "Завяршыць тэст", "Ավարտել թեստը", "ტესტის დასრულება", "Testi tamamlamak", "Finish the test", "Terminar el test", "Finalizar o teste", "إنهاء الاختبار", "Testi bitir", "टेस्ट समाप्त करें", "テストを終了", "테스트 종료", "Test beenden"],
  "Пока поддерживаются только файлы .docx": ["Пока поддерживаются только файлы .docx", "Faqat .docx fayllar qo'llab-quvvatlanadi", "Әзірге тек .docx файлдары қолдау көрсетіледі", "Поки що підтримуються лише файли .docx", "Hələlik yalnız .docx faylları dəstəklənir", "Азырынча .docx файлдары гана колдоого алынат", "Ҳоло танҳо файлҳои .docx дастгирӣ мешаванд", "Пакуль падтрымліваюцца толькі файлы .docx", "Առայժմ աջակցվում են միայն .docx ֆայլերը", "ჯერჯერობით მხოლოდ .docx ფაილებია მხარდაჭერილი", "Häzirlikçe diňe .docx faýllary goldanýar", "Only .docx files are supported for now", "Por ahora solo se admiten archivos .docx", "Por enquanto, apenas arquivos .docx são suportados", "حالياً يتم دعم ملفات .docx فقط", "Şu an yalnızca .docx dosyaları destekleniyor", "फ़िलहाल केवल .docx फ़ाइलें समर्थित हैं", "現在は.docxファイルのみ対応しています", "현재는 .docx 파일만 지원됩니다", "Derzeit werden nur .docx-Dateien unterstützt"],
  "Ошибка загрузки шаблона": ["Ошибка загрузки шаблона", "Shablonni yuklashda xato", "Үлгіні жүктеу қатесі", "Помилка завантаження шаблону", "Şablonu yükləyərkən xəta", "Шаблонду жүктөөдө ката", "Хатогӣ ҳангоми боргирии андоза", "Памылка загрузкі шаблону", "Ձևանմուշը վերբեռնելու սխալ", "შაბლონის ატვირთვის შეცდომა", "Şablony ýüklemekde ýalňyşlyk", "Error uploading the template", "Error al cargar la plantilla", "Erro ao carregar o modelo", "خطأ في تحميل القالب", "Şablon yüklenirken hata", "टेम्पलेट अपलोड करने में त्रुटि", "テンプレートのアップロードエラー", "템플릿 업로드 오류", "Fehler beim Hochladen der Vorlage"],
  "Удалить шаблон?": ["Удалить шаблон?", "Shablonni o'chirish?", "Үлгіні жою керек пе?", "Видалити шаблон?", "Şablon silinsin?", "Шаблонду өчүрөсүзбү?", "Андозаро нест кунам?", "Выдаліць шаблон?", "Ջնջե՞լ ձևանմուշը", "წავშალო შაბლონი?", "Şablony pozmalymy?", "Delete template?", "¿Eliminar plantilla?", "Excluir modelo?", "هل تريد حذف القالب؟", "Şablon silinsin mi?", "टेम्पलेट हटाएं?", "テンプレートを削除しますか？", "템플릿을 삭제하시겠습니까?", "Vorlage löschen?"],
  "Это действие нельзя отменить": ["Это действие нельзя отменить", "Bu amalni ortga qaytarib bo'lmaydi", "Бұл әрекетті болдырмауға болмайды", "Цю дію не можна скасувати", "Bu əməliyyat geri qaytarıla bilməz", "Бул аракетти артка кайтарууга болбойт", "Ин амалро бекор кардан мумкин нест", "Гэтае дзеянне нельга адрабіць", "Այս գործողությունը հնարավոր չէ չեղարկել", "ამ მოქმედების გაუქმება შეუძლებელია", "Bu hereketi yatyryp bolmaýar", "This action cannot be undone", "Esta acción no se puede deshacer", "Esta ação não pode ser desfeita", "لا يمكن التراجع عن هذا الإجراء", "Bu işlem geri alınamaz", "यह क्रिया पूर्ववत नहीं की जा सकती", "この操作は元に戻せません", "이 작업은 취소할 수 없습니다", "Diese Aktion kann nicht rückgängig gemacht werden"],
  "Документы и шаблоны": ["Документы и шаблоны", "Hujjat shablonlari", "Құжаттар мен үлгілер", "Документи та шаблони", "Sənədlər və şablonlar", "Документтер жана шаблондор", "Ҳуҷҷатҳо ва андозаҳо", "Дакументы і шаблоны", "Փաստաթղթեր և ձևանմուշներ", "დოკუმენტები და შაბლონები", "Resminamalar we şablonlar", "Documents and templates", "Documentos y plantillas", "Documentos e modelos", "المستندات والقوالب", "Belgeler ve şablonlar", "दस्तावेज़ और टेम्पलेट्स", "文書とテンプレート", "문서 및 템플릿", "Dokumente und Vorlagen"],
  "Загружаем и анализируем...": ["Загружаем и анализируем...", "Yuklanmoqda...", "Жүктеп, талдап жатырмыз...", "Завантажуємо і аналізуємо...", "Yüklənir və təhlil edilir...", "Жүктеп жатабыз жана талдап жатабыз...", "Бор карда истода таҳлил мекунем...", "Загружаем і аналізуем...", "Բեռնում և վերլուծում ենք...", "იტვირთება და მუშავდება...", "Ýüklenýär we seljerilýär...", "Uploading and analyzing...", "Cargando y analizando...", "Carregando e analisando...", "جارٍ التحميل والتحليل...", "Yükleniyor ve analiz ediliyor...", "अपलोड और विश्लेषण हो रहा है...", "アップロードして分析中...", "업로드 및 분석 중...", "Wird hochgeladen und analysiert..."],
  "Перетащите Word-шаблон (.docx) сюда или нажмите": ["Перетащите Word-шаблон (.docx) сюда или нажмите", "Word shablonini (.docx) tashlang yoki tanlang", "Word үлгісін (.docx) осында сүйреп әкеліңіз немесе басыңыз", "Перетягніть Word-шаблон (.docx) сюди або натисніть", "Word şablonunu (.docx) buraya atın və ya klikləyin", "Word шаблонун (.docx) бул жерге сүйрөңүз же басыңыз", "Андозаи Word-ро (.docx) ба ин ҷо кашед ё зер кунед", "Перацягніце Word-шаблон (.docx) сюды або націсніце", "Քաշեք Word ձևանմուշը (.docx) այստեղ կամ սեղմեք", "გადმოიტანეთ Word შაბლონი (.docx) აქ ან დააჭირეთ", "Word şablonyny (.docx) şu ýere süýräň ýa-da basyň", "Drag a Word template (.docx) here or click", "Arrastre una plantilla de Word (.docx) aquí o haga clic", "Arraste um modelo do Word (.docx) aqui ou clique", "اسحب قالب Word (.docx) هنا أو انقر", "Word şablonunu (.docx) buraya sürükleyin veya tıklayın", "Word टेम्पलेट (.docx) यहां खींचें या क्लिक करें", "Wordテンプレート（.docx）をここにドラッグするかクリック", "Word 템플릿(.docx)을 여기로 드래그하거나 클릭하세요", "Word-Vorlage (.docx) hierher ziehen oder klicken"],
  "Пока поддерживается только .docx": ["Пока поддерживается только .docx", "Faqat .docx qo'llab-quvvatlanadi", "Әзірге тек .docx қолдау көрсетіледі", "Поки що підтримується лише .docx", "Hələlik yalnız .docx dəstəklənir", "Азырынча .docx гана колдоого алынат", "Ҳоло танҳо .docx дастгирӣ мешавад", "Пакуль падтрымліваецца толькі .docx", "Առայժմ աջակցվում է միայն .docx-ը", "ჯერჯერობით მხოლოდ .docx-ია მხარდაჭერილი", "Häzirlikçe diňe .docx goldanýar", "Only .docx is supported for now", "Por ahora solo se admite .docx", "Por enquanto, apenas .docx é suportado", "حالياً يتم دعم .docx فقط", "Şu an yalnızca .docx destekleniyor", "फ़िलहाल केवल .docx समर्थित है", "現在は.docxのみ対応しています", "현재는 .docx만 지원됩니다", "Derzeit wird nur .docx unterstützt"],
  "Шаблонов пока нет": ["Шаблонов пока нет", "Hali shablonlar yo'q", "Әзірге үлгілер жоқ", "Поки що шаблонів немає", "Hələ şablon yoxdur", "Азырынча шаблондор жок", "Ҳоло андозаҳо нестанд", "Пакуль шаблонаў няма", "Դեռ ձևանմուշներ չկան", "შაბლონები ჯერ არ არის", "Häzirlikçe şablon ýok", "No templates yet", "Aún no hay plantillas", "Ainda não há modelos", "لا توجد قوالب حتى الآن", "Henüz şablon yok", "अभी तक कोई टेम्पलेट नहीं है", "テンプレートはまだありません", "아직 템플릿이 없습니다", "Noch keine Vorlagen"],
  "С плейсхолдерами": ["С плейсхолдерами", "Plейsxolderlar bilan", "Плейсхолдерлермен", "З плейсхолдерами", "Placeholder-lərlə", "Плейсхолдерлер менен", "Бо ҷойгузинҳо", "З плэйсхолдэрамі", "Placeholder-ներով", "პლეისჰოლდერებით", "Placeholder-ler bilen", "With placeholders", "Con marcadores", "Com marcadores", "مع عناصر نائبة", "Yer tutuculu", "प्लेसहोल्डर के साथ", "プレースホルダー付き", "플레이스홀더 포함", "Mit Platzhaltern"],
  "Свободный текст": ["Свободный текст", "Erkin matn", "Еркін мәтін", "Вільний текст", "Sərbəst mətn", "Эркин текст", "Матни озод", "Вольны тэкст", "Ազատ տեքստ", "თავისუფალი ტექსტი", "Erkin tekst", "Free-form text", "Texto libre", "Texto livre", "نص حر", "Serbest metin", "मुक्त पाठ", "自由記述", "자유 텍스트", "Freitext"],
  "Загрузите Word-шаблон, опишите что вставить — получите готовый PDF": ["Загрузите Word-шаблон, опишите что вставить — получите готовый PDF", "Word shablonini yuklang, matnda nimani o'zgartirish kerakligini yozing — tayyor PDF olasiz", "Word үлгісін жүктеңіз, нені кірістіру керегін жазыңыз — дайын PDF аласыз", "Завантажте Word-шаблон, опишіть що вставити — отримайте готовий PDF", "Word şablonunu yükləyin, nə əlavə etmək lazım olduğunu yazın — hazır PDF alın", "Word шаблонун жүктөңүз, эмнени коюу керектигин жазыңыз — даяр PDF аласыз", "Андозаи Word-ро бор кунед, нависед чиро ворид кардан лозим аст — PDF-и тайёр гиред", "Загрузіце Word-шаблон, апішыце што ўставіць — атрымайце гатовы PDF", "Վերբեռնեք Word ձևանմուշը, նկարագրեք ինչ տեղադրել — ստացեք պատրաստի PDF", "ატვირთეთ Word შაბლონი, აღწერეთ რა უნდა ჩასვათ — მიიღეთ მზა PDF", "Word şablonyny ýükläň, näme goşmalydygyny ýazyň — taýýar PDF alyň", "Upload a Word template, describe what to insert — get a ready PDF", "Sube una plantilla de Word, describe qué insertar — obtén un PDF listo", "Envie um modelo do Word, descreva o que inserir — receba um PDF pronto", "ارفع قالب Word، وصف ما تريد إدراجه — واحصل على PDF جاهز", "Word şablonu yükleyin, neyin ekleneceğini yazın — hazır PDF alın", "Word टेम्पलेट अपलोड करें, बताएं क्या डालना है — तैयार PDF पाएं", "Wordテンプレートをアップロードし、挿入内容を記入すると完成PDFが得られます", "Word 템플릿을 업로드하고 삽입할 내용을 설명하면 완성된 PDF를 받습니다", "Word-Vorlage hochladen, beschreiben was eingefügt werden soll — fertiges PDF erhalten"],
  "Шаблон не найден": ["Шаблон не найден", "Shablon topilmadi", "Үлгі табылмады", "Шаблон не знайдено", "Şablon tapılmadı", "Шаблон табылган жок", "Андоза ёфт нашуд", "Шаблон не знойдзены", "Ձևանմուշը չի գտնվել", "შაბლონი ვერ მოიძებნა", "Şablon tapylmady", "Template not found", "Plantilla no encontrada", "Modelo não encontrado", "لم يتم العثور على القالب", "Şablon bulunamadı", "टेम्पलेट नहीं मिला", "テンプレートが見つかりません", "템플릿을 찾을 수 없습니다", "Vorlage nicht gefunden"],
  "Поля в шаблоне:": ["Поля в шаблоне:", "Shablondagi maydonlar:", "Үлгідегі өрістер:", "Поля у шаблоні:", "Şablondakı sahələr:", "Шаблондогу талаалар:", "Майдонҳо дар андоза:", "Палі ў шаблоне:", "Ձևանմուշի դաշտերը՝", "შაბლონის ველები:", "Şablondaky meýdanlar:", "Fields in the template:", "Campos en la plantilla:", "Campos no modelo:", "الحقول في القالب:", "Şablondaki alanlar:", "टेम्पलेट में फ़ील्ड:", "テンプレート内のフィールド:", "템플릿 필드:", "Felder in der Vorlage:"],
  "Например: ФИО — Иванов Иван, Дата — 15.07.2026": ["Например: ФИО — Иванов Иван, Дата — 15.07.2026", "Masalan: FIO — Ivanov Ivan, Sana — 15.07.2026", "Мысалы: Т.А.Ә. — Иванов Иван, Күні — 15.07.2026", "Наприклад: ПІБ — Іванов Іван, Дата — 15.07.2026", "Məsələn: Ad Soyad — İvanov İvan, Tarix — 15.07.2026", "Мисалы: Аты-жөнү — Иванов Иван, Күнү — 15.07.2026", "Масалан: Ному насаб — Иванов Иван, Сана — 15.07.2026", "Напрыклад: ПІБ — Іваноў Іван, Дата — 15.07.2026", "Օրինակ՝ Անուն Ազգանուն — Իվանով Իվան, Ամսաթիվ — 15.07.2026", "მაგალითად: სახელი გვარი — ივანოვ ივანე, თარიღი — 15.07.2026", "Meselem: F.A.A. — Iwanow Iwan, Sene — 15.07.2026", "Example: Full name — John Smith, Date — 15.07.2026", "Ejemplo: Nombre completo — Juan Pérez, Fecha — 15.07.2026", "Exemplo: Nome completo — João Silva, Data — 15.07.2026", "مثال: الاسم الكامل — إيفانوف إيفان، التاريخ — 15.07.2026", "Örnek: Ad Soyad — Ivanov Ivan, Tarih — 15.07.2026", "उदाहरण: पूरा नाम — इवानोव इवान, तारीख़ — 15.07.2026", "例：氏名 — イワノフ・イワン、日付 — 2026年7月15日", "예: 성명 — 이바노프 이반, 날짜 — 2026.07.15", "Beispiel: Name — Iwanow Iwan, Datum — 15.07.2026"],
  "Опишите, что нужно изменить в документе...": ["Опишите, что нужно изменить в документе...", "Nimani o'zgartirish kerakligini yozing...", "Құжатта нені өзгерту керегін жазыңыз...", "Опишіть, що потрібно змінити в документі...", "Sənəddə nəyi dəyişmək lazım olduğunu yazın...", "Документте эмнени өзгөртүү керектигин жазыңыз...", "Нависед, ки дар ҳуҷҷат чиро тағйир додан лозим аст...", "Апішыце, што трэба змяніць у дакуменце...", "Նկարագրեք, ինչ պետք է փոխել փաստաթղթում...", "აღწერეთ, რა უნდა შეიცვალოს დოკუმენტში...", "Resminamada näme üýtgetmelidigini ýazyň...", "Describe what needs to change in the document...", "Describa qué debe cambiar en el documento...", "Descreva o que precisa mudar no documento...", "صف ما يجب تغييره في المستند...", "Belgede neyin değişmesi gerektiğini yazın...", "बताएं दस्तावेज़ में क्या बदलना है...", "文書内で変更が必要な内容を記入してください...", "문서에서 변경할 내용을 설명하세요...", "Beschreiben Sie, was im Dokument geändert werden soll..."],
  "История генераций": ["История генераций", "Yaratilganlar", "Жасалғандар тарихы", "Історія генерацій", "Yaradılanlar tarixçəsi", "Түзүлгөндөр тарыхы", "Таърихи офаридашуда", "Гісторыя генерацый", "Ստեղծումների պատմություն", "გენერაციების ისტორია", "Döredilenleriň taryhy", "Generation history", "Historial de generaciones", "Histórico de gerações", "سجل الإنشاءات", "Oluşturma geçmişi", "जनरेशन इतिहास", "生成履歴", "생성 기록", "Generierungsverlauf"],
  "Пока ничего не сгенерировано": ["Пока ничего не сгенерировано", "Hali hech narsa yaratilmagan", "Әзірге ештеңе жасалмаған", "Поки що нічого не згенеровано", "Hələ heç nə yaradılmayıb", "Азырынча эч нерсе түзүлгөн жок", "Ҳоло чизе тавлид нашудааст", "Пакуль нічога не згенеравана", "Դեռ ոչինչ ստեղծված չէ", "ჯერ არაფერია გენერირებული", "Häzirlikçe hiç zat döredilmedi", "Nothing generated yet", "Aún no se ha generado nada", "Nada foi gerado ainda", "لم يتم إنشاء أي شيء بعد", "Henüz bir şey oluşturulmadı", "अभी तक कुछ भी जनरेट नहीं हुआ", "まだ何も生成されていません", "아직 생성된 것이 없습니다", "Noch nichts generiert"],
  "Готовим документ...": ["Готовим документ...", "Tayyorlanmoqda...", "Құжат дайындалуда...", "Готуємо документ...", "Sənəd hazırlanır...", "Документ даярдалууда...", "Ҳуҷҷат омода шуда истодааст...", "Рыхтуем дакумент...", "Փաստաթուղթը պատրաստվում է...", "დოკუმენტის მომზადება...", "Resminama taýýarlanýar...", "Preparing the document...", "Preparando el documento...", "Preparando o documento...", "جارٍ إعداد المستند...", "Belge hazırlanıyor...", "दस्तावेज़ तैयार किया जा रहा है...", "文書を準備中...", "문서 준비 중...", "Dokument wird vorbereitet..."],
  "Скачать PDF": ["Скачать PDF", "PDF yuklab olish", "PDF жүктеп алу", "Завантажити PDF", "PDF-i yüklə", "PDF жүктөп алуу", "Боргирии PDF", "Спампаваць PDF", "Ներբեռնել PDF", "PDF-ის ჩამოტვირთვა", "PDF ýükle", "Download PDF", "Descargar PDF", "Baixar PDF", "تنزيل PDF", "PDF indir", "PDF डाउनलोड करें", "PDFをダウンロード", "PDF 다운로드", "PDF herunterladen"],
  "Персональный AI-ассистент": ["Персональный AI-ассистент", "Shaxsiy AI-yordamchingiz", "Жеке AI-көмекші", "Персональний AI-асистент", "Şəxsi AI-köməkçi", "Жеке AI-жардамчы", "Ёрдамчии шахсии AI", "Персанальны AI-памочнік", "Անհատական AI-օգնական", "პერსონალური AI-ასისტენტი", "Şahsy AI-kömekçi", "Your personal AI assistant", "Tu asistente de IA personal", "Seu assistente de IA pessoal", "مساعدك الشخصي بالذكاء الاصطناعي", "Kişisel AI asistanınız", "आपका व्यक्तिगत AI सहायक", "パーソナルAIアシスタント", "개인 AI 어시스턴트", "Ihr persönlicher KI-Assistent"],
  "Email должен содержать только латинские символы. Проверьте раскладку клавиатуры.": ["Email должен содержать только латинские символы. Проверьте раскладку клавиатуры.", "Email faqat lotin harflaridan iborat bo'lishi kerak. Klaviatura tilini tekshiring.", "Email тек латын әріптерінен тұруы керек. Пернетақта тілін тексеріңіз.", "Email має містити лише латинські символи. Перевірте розкладку клавіатури.", "Email yalnız latın hərflərindən ibarət olmalıdır. Klaviatura dilini yoxlayın.", "Email жалаң латын тамгаларынан турушу керек. Клавиатура тилин текшериңиз.", "Email бояд танҳо аз ҳарфҳои лотинӣ иборат бошад. Забони клавиатураро санҷед.", "Email павінен змяшчаць толькі лацінскія сімвалы. Праверце раскладку клавіятуры.", "Email-ը պետք է պարունակի միայն լատինատառ նիշեր։ Ստուգեք ստեղնաշարի լեզուն։", "Email უნდა შეიცავდეს მხოლოდ ლათინურ სიმბოლოებს. შეამოწმეთ კლავიატურის ენა.", "Email diňe latyn harplaryndan ybarat bolmaly. Klawiatura dilini barlaň.", "Email must contain only Latin characters. Check your keyboard layout.", "El correo debe contener solo caracteres latinos. Revise la distribución del teclado.", "O e-mail deve conter apenas caracteres latinos. Verifique o layout do teclado.", "يجب أن يحتوي البريد الإلكتروني على أحرف لاتينية فقط. تحقق من تخطيط لوحة المفاتيح.", "E-posta yalnızca Latin karakterler içermelidir. Klavye dilini kontrol edin.", "ईमेल में केवल लैटिन अक्षर होने चाहिए। कीबोर्ड लेआउट जांचें।", "メールアドレスにはラテン文字のみを使用してください。キーボード配列を確認してください。", "이메일에는 라틴 문자만 포함되어야 합니다. 키보드 레이아웃을 확인하세요.", "Die E-Mail darf nur lateinische Zeichen enthalten. Prüfen Sie Ihr Tastaturlayout."],
  "Пароль должен содержать только латинские символы и цифры.": ["Пароль должен содержать только латинские символы и цифры.", "Parol faqat lotin harflari va raqamlardan iborat bo'lishi kerak.", "Құпия сөз тек латын әріптері мен сандардан тұруы керек.", "Пароль має містити лише латинські символи та цифри.", "Şifrə yalnız latın hərfləri və rəqəmlərdən ibarət olmalıdır.", "Сыр сөз жалаң латын тамгалары жана сандардан турушу керек.", "Рамз бояд танҳо аз ҳарфҳои лотинӣ ва рақамҳо иборат бошад.", "Пароль павінен змяшчаць толькі лацінскія сімвалы і лічбы.", "Գաղտնաբառը պետք է պարունակի միայն լատինատառ նիշեր և թվեր։", "პაროლი უნდა შეიცავდეს მხოლოდ ლათინურ სიმბოლოებსა და ციფრებს.", "Parol diňe latyn harplary we sanlardan ybarat bolmaly.", "Password must contain only Latin characters and digits.", "La contraseña debe contener solo caracteres latinos y números.", "A senha deve conter apenas caracteres latinos e números.", "يجب أن تحتوي كلمة المرور على أحرف لاتينية وأرقام فقط.", "Şifre yalnızca Latin karakterler ve rakamlar içermelidir.", "पासवर्ड में केवल लैटिन अक्षर और अंक होने चाहिए।", "パスワードにはラテン文字と数字のみを使用してください。", "비밀번호에는 라틴 문자와 숫자만 포함되어야 합니다.", "Das Passwort darf nur lateinische Zeichen und Ziffern enthalten."],
  "или": ["или", "yoki", "немесе", "або", "yaxud", "же", "ё", "або", "կամ", "ან", "ýa-da", "or", "o", "ou", "أو", "veya", "या", "または", "또는", "oder"],
};

// One-off pluralized message (skip count differs by language) — handled as a
// function rather than a static dict entry.
export function formatSkippedWarning(lang: Lang, count: number): string {
  const label: Record<Lang, string> = {
    ru: `Внимание: ${count} изменени${count === 1 ? "е" : "я"} не удалось однозначно применить и было пропущено`,
    uz: `Diqqat: ${count} ta o'zgartirish aniq joyi topilmagani uchun o'tkazib yuborildi`,
    kk: `Назар аударыңыз: ${count} өзгеріс дәл қолданылмай, өткізіп жіберілді`,
    uk: `Увага: ${count} зміну не вдалося однозначно застосувати, її пропущено`,
    az: `Diqqət: ${count} dəyişiklik birmənalı tətbiq edilə bilmədi və buraxıldı`,
    ky: `Кулак салыңыз: ${count} өзгөртүү так колдонулбай, өткөрүлүп жиберилди`,
    tg: `Диққат: ${count} тағйирот бе абҳом татбиқ нашуд ва гузашта шуд`,
    be: `Увага: ${count} змену не атрымалася адназначна ўжыць, яе прапушчана`,
    hy: `Ուշադրություն. ${count} փոփոխություն հստակ չկիրառվեց և բաց թողնվեց`,
    ka: `ყურადღება: ${count} ცვლილება ცალსახად ვერ გავრცელდა და გამოტოვებულია`,
    tk: `Üns beriň: ${count} üýtgeşme takyk ulanylmady we geçirildi`,
    en: `Note: ${count} change${count === 1 ? "" : "s"} couldn't be applied unambiguously and ${count === 1 ? "was" : "were"} skipped`,
    es: `Nota: ${count} cambio${count === 1 ? "" : "s"} no se pudo aplicar sin ambigüedad y fue omitido`,
    pt: `Nota: ${count} alteraç${count === 1 ? "ão" : "ões"} não pôde ser aplicada sem ambiguidade e foi ignorada`,
    ar: `ملاحظة: تعذر تطبيق ${count} تغيير(ات) بشكل قاطع وتم تخطيه`,
    tr: `Not: ${count} değişiklik net şekilde uygulanamadı ve atlandı`,
    hi: `ध्यान दें: ${count} बदलाव स्पष्ट रूप से लागू नहीं हो सका और छोड़ दिया गया`,
    ja: `注意: ${count}件の変更を一意に適用できず、スキップされました`,
    ko: `참고: ${count}개의 변경 사항을 명확히 적용할 수 없어 건너뛰었습니다`,
    de: `Hinweis: ${count} Änderung${count === 1 ? "" : "en"} konnte${count === 1 ? "" : "n"} nicht eindeutig angewendet werden und wurde${count === 1 ? "" : "n"} übersprungen`,
  };
  return label[lang];
}

export function translate(lang: Lang, ru: string): string {
  const row = UI_DICT[ru];
  if (!row) return ru;
  return row[LANG_INDEX[lang]] || ru;
}

// For content authored directly as a 20-slot array (LANGS order) rather than
// looked up by a Russian source string — e.g. the onboarding tutorial's copy.
export function pick<T>(lang: Lang, arr: readonly T[]): T {
  return arr[LANG_INDEX[lang]] ?? arr[0];
}
